name: drone
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  flutter_hooks: ^0.18.2+1
  json_annotation: ^4.4.0
  go_router: ^6.0.0
  hive_flutter: ^1.1.0
  ionicons: ^0.2.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  repo_repository:
    path: packages/repo_repository
  auth_repository:
    path: packages/auth_repository
  local_data_source:
    path: packages/local_data_source
  form_input:
    path: packages/form_input
  window_manager: ^0.2.7
  formz: ^0.4.1
  intl: ^0.17.0
  bloc_concurrency: ^0.2.0
  flutter_launcher_icons: "^0.11.0"
  fl_chart: ^0.55.2
  get_it: ^7.2.0
  awesome_notifications: ^0.7.4+1
  notification_repository:
    path: packages/notification_repository
dev_dependencies:
  analyzer:
  build_runner: any
  go_router_builder: any
  build_verify: any
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: any
  hive_generator: 
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Dongle
      fonts:
        - asset: fonts/Dongle-Light.ttf
          weight: 300
        - asset: fonts/Dongle-Regular.ttf
          weight: 400
        - asset: fonts/Dongle-Bold.ttf
          weight: 700
    - family: Signika
      fonts:
        - asset: fonts/Signika-Light.ttf
          weight: 300
        - asset: fonts/Signika-Regular.ttf
          weight: 400
        - asset: fonts/Signika-Medium.ttf
          weight: 500
        - asset: fonts/Signika-Bold.ttf
          weight: 700

flutter_icons:
  image_path_android: "assets/logo.png"
  android: "drone"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 
