name: notification_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  
dependencies:
  rxdart: ^0.27.7
  local_data_source: 
    path: ../local_data_source
  drone_dart: 
    path: D:/Drone-sdk/drone-dart
  awesome_notifications: ^0.7.4+1