name: local_data_source
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
environment:
  sdk: '>=2.18.4 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

dependencies:
  equatable: ^2.0.3
  hive: ^2.2.3
  drone_dart: 
    path: D:/Drone-sdk/drone-dart
  rxdart: ^0.27.7
